"""migration

Revision ID: 3711f32d0f84
Revises: 68ab12dd4418
Create Date: 2024-11-26 19:36:37.985958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3711f32d0f84'
down_revision: Union[str, None] = '68ab12dd4418'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('tg_id', sa.String(), nullable=False))
    op.add_column('about', sa.Column('dialog', sa.String(), nullable=False))
    op.add_column('about', sa.Column('tread_id', sa.String(), nullable=False))
    op.drop_column('about', 'what_can')
    op.drop_column('about', 'all_text')
    op.drop_column('about', 'who_need')
    op.drop_column('about', 'who')
    op.drop_column('about', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('about', sa.Column('who', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('about', sa.Column('who_need', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('about', sa.Column('all_text', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('about', sa.Column('what_can', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('about', 'tread_id')
    op.drop_column('about', 'dialog')
    op.drop_column('about', 'tg_id')
    # ### end Alembic commands ###
