"""описание миграции

Revision ID: 68ab12dd4418
Revises: d64443471843
Create Date: 2024-11-12 18:05:13.763350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68ab12dd4418'
down_revision: Union[str, None] = 'd64443471843'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('about', sa.Column('all_text', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('about', 'all_text')
    # ### end Alembic commands ###
